### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by jadjoubran** [jadjoubran/laravel-angular#1]
As this repository will most likely be a Laravel (and Lumen eventually?) package, here are the expected features:

* Response Macros (same as in the previous version)
* A lightweight CORS middleware

Feel free to add suggestions
Thanks!

**Comment by jadsalhani** [comment]
This is where I step in :D

**Comment by jadjoubran** [comment]
@jadsalhani You mean the other [repo](https://github.com/jadjoubran/angular-laravel/issues/1) 😄

**Comment by birkansava** [comment]
I just can't wait for use that with Lumen... :D

**Comment by jadjoubran** [comment]
@birkansava I'll be working on a package that has Response macros only for now, which will work with Lumen as well

**Comment by jadjoubran** [comment]
@birkansava https://github.com/jadjoubran/laravel-angular

**Comment by birkansava** [comment]
@jadjoubran I actually made it work with Lumen :) but still waiting for Angular2

**Comment by vtnhan** [comment]
We're waiting for Angular 2 template :)

**Comment by jadjoubran** [comment]
Hi @vtnhan 
What do you mean exactly? Can you give an example?

**Comment by vtnhan** [comment]
Like this but now is Angular 2 :)

![image](https://user-images.githubusercontent.com/1813667/28870404-5991af1e-77aa-11e7-9f11-dfcfd6ce772c.png)

**Comment by jadjoubran** [comment]
@vtnhan This is currently taken care of by the [Angular CLI](https://cli.angular.io/)
They do an amazing job at generating, serving, deploying (and much more) your Angular projects
