### ISSUE TITLE
compatible with laravel 5.1?

### ISSUE THREAD

**Issue by steros** [jadjoubran/laravel-angular#10]
is this package compatible with laravel 5.1?
because I'm getting this error when running
`php artisan laravelangular:install`

> [Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                         
  Class Jadjoubran\LaravelAngular\Provider\LaravelAngularServiceProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (  
  Illuminate\Support\ServiceProvider::register)

**Comment by jadjoubran** [comment]
Hi @steros 
I think it doesn't work with 5.1 because of a change in the service provider
Would you be able to send a PR?
Thanks!

**Comment by steros** [comment]
Hi @jadjoubran 
I think unfortunately I won't be able. We just decided to switch to 5.5 anyway.
So the problem solved itself so to speak.

**Comment by jadjoubran** [comment]
Cool!
