### ISSUE TITLE
Angular placement

### ISSUE THREAD

**Issue by shahzad-saddam** [jadjoubran/laravel-angular#19]
There is no information or guidance on where to put the angular in while using this package

**Comment by jadjoubran** [comment]
Hi @shahzad-saddam 
Thanks for bringing this to my attention
We had docs for the angular installation but I just realized that the sidebar link for that page was broken
I just fixed it and it's [here](https://laravel-angular.io/docs/1/angular-install/)

Feel free to re-open if you've got additional questions!

**Comment by shahzad-saddam** [comment]
Thanks
