### ISSUE TITLE
Erorr  php artisan laravelangular:install

### ISSUE THREAD

**Issue by MarketingLimited** [jadjoubran/laravel-angular#7]
Method Jadjoubran\LaravelAngular\Command\InstallCommand::handle() does not exist

**Comment by bumpety** [comment]
Jadjoubran\LaravelAngular\Command\InstallCommand::handle()

to

Jadjoubran\LaravelAngular\Command\InstallCommand::fire()

**Comment by jadjoubran** [comment]
Fixed in #8
